### ISSUE TITLE
Porting to Python 3 or futurize to support Py2/3

### ISSUE THREAD

**Issue by MaxPeal** [opoplawski/InstantMirror#1]
please do a Porting to Python 3 or futurize to support Py2 and Py3

**Comment by opoplawski** [comment]
This would really need a complete rewrite to mod_wsgi as mod_python is dead.  I'm not sure it's worth doing.

**Comment by opoplawski** [comment]
This has now been ported to python 3 using webob.

**Comment by MaxPeal** [comment]
Thank you, i give it a try!
